# =====================================================================
# Kubernetes Secrets & ConfigMap
# Sensitive credentials & non-sensitive environment configuration
# =====================================================================

apiVersion: v1
kind: Secret
metadata:
  name: portfolio-secrets
  namespace: portfolio
type: Opaque
stringData:
  MSSQL_SA_PASSWORD: "YourStrong@Password123"
  DB_PASSWORD: "YourStrong@Password123"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: portfolio-config
  namespace: portfolio
data:
  PORT_BACKEND: "8080"
  PORT_FRONTEND: "3000"
  DATASOURCE_URL: "jdbc:sqlserver://sqlserver-service:1433;databaseName=master;encrypt=true;trustServerCertificate=true"
  DB_USERNAME: "sa"
  SQL_INIT_MODE: "never"
  FRONTEND_URL: "http://localhost:3000"
  NEXT_PUBLIC_API_URL: "http://localhost:8080"
